### ISSUE TITLE
no module named batteqns

### ISSUE THREAD

**Issue by wigging** [matthewpklein/battsimpy#1]
In the `battsimpy` directory I run the following command:

```
python testdriver.py model_conffile.conf sim_conffile.conf
```

The command returns an error of:

```
No module named 'batteqns'
```

Is the `batteqns` module missing from the repository or is it something I need to create?

**Comment by wigging** [comment]
Closing this because the repository appears to be no longer maintained.

**Comment by sameer9406** [comment]
I spent some time on this code and got it successfully running. You need to copy and paste all the helper and battery model files where the testdriver.py is located
