### ISSUE TITLE
update to python 3

### ISSUE THREAD

**Issue by wigging** [matthewpklein/battsimpy#2]
The code seems to be written for Python 2. Is there a reason for this? Is it possible to update the project to the latest version of Python which is Python 3.6?

**Comment by wigging** [comment]
Closing this because the repository appears to be no longer maintained.

**Comment by sameer9406** [comment]
Not sure why, but it runs good with python 2.7. If you are using windows then parallel to python 3 you can also install anaconda 2 and work with its command prompt.
